title: "Julius Portfolio"
description: "Hi! I am Julius Villareal and I enjoy bringing ideas into life."
author:
  name: Julius Villareal
  email: villareal.jm.napiza@gmail.com
remote_theme: jekyll/minima@d4d779a
repository: "jmnvillareal08/jmnvillareal08.github.io"
minima:
  hide_site_feed_link: true
  skin: auto
  social_links:
  - title: Jekyll repository at GitHub
    icon: github
    url: "https://github.com/jmnvillareal08"
  - title: LinkedIn Link
    icon: linkedin
    url: "https://www.linkedin.com/in/julius-marwin-villareal-381975198/"
    